version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video
    networks:
      video: {}
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    networks:
      video: {} 

  caddy:
    image: caddy:2.3.0
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      video: {}

networks:
  video: {}

volumes:
  db: {}
  caddy: {}